language: php

php:
  - '7.0'
  - '7.1'

env:
  - SH=bash

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install bc -y

install:
  - travis_retry composer install --no-interaction --prefer-dist --no-suggest

before_script:
  - travis_retry composer self-update
  - travis_retry composer install --prefer-source --no-interaction --dev

script:
  - vendor/bin/phpunit --coverage-clover build/logs/clover.xml
  - vendor/bin/phpcs --version && echo && vendor/bin/phpcs -p --standard=PSR2 src
  - bash -c "[ $(echo "$(grep '^  Lines' builds/coverage.txt | awk '{print $2;}' | tr -d '%') >= 75" | bc) -eq "1" ]"